### ISSUE TITLE
Add a new CNBi build type: git repo

### ISSUE THREAD

**Issue by codificat** [thoth-station/odh-dashboard#11]
While it's not in the original specification of the custom notebook images functionality, the meteor-operator/cnbi controller does have the capability to create a new custom image by building from a git repository.

[Here](https://github.com/thoth-station/meteor-operator/blob/a60a8ac5f4bdc0db7964b53c6cf267ec02fbf270/config/samples/meteor_v1alpha1_customruntimeenvironment_git-repository.yaml) is a sample `CustomRuntimeEnvironment` for this type of custom build:

``` yaml
---
apiVersion: meteor.zone/v1alpha1
kind: CustomRuntimeEnvironment
metadata:
  name: elyra-aidevsecops-tutorial
  labels:
    app.kubernetes.io/created-by: cpe-_a-meteor.zone-CRE-v0.1.0
  annotations:
    opendatahub.io/notebook-image-name: Elyra DevSecOps Tutorial
    opendatahub.io/notebook-image-desc: Build from the Elyra Tutorial
    opendatahub.io/notebook-image-creator: codificat
spec:
  buildType: GitRepository
  repository: https://github.com/AICoE/elyra-aidevsecops-tutorial
  gitRef: master
```

It should (hopefully) be relatively easy to adapt the UI for the *Import existing image* type to add the option to *Build from a Git Repo*.

## Acceptance criteria

- [ ] A new way to add a new image exists: *Build a new image from a Git repository*
- [ ] The UI requests the *repository*, (optional) *git reference*, *name* and *description* and creates a matching `CustomRuntimeEnvironment`
- [ ] The UI correctly monitors/informs of the progress/status of the CRE
